
let historyQuestions = [
    {
      question: "In welchem Jahr endete der Zweite Weltkrieg?",
      answer_1: "1943",
      answer_2: "1945",
      answer_3: "1950",
      answer_4: "1939",
      right_answer: 2,
    },
    {
      question: "Wer war der erste Präsident der Vereinigten Staaten?",
      answer_1: "George Washington",
      answer_2: "Thomas Jefferson",
      answer_3: "Abraham Lincoln",
      answer_4: "John Adams",
      right_answer: 1,
    },
    {
      question: "In welchem Jahr endete der Erste Weltkrieg?",
      answer_1: "1914",
      answer_2: "1917",
      answer_3: "1918",
      answer_4: "1920",
      right_answer: 3,
    },
    {
      question:`Welcher berühmte Herrscher regierte im antiken Rom und wurde am 15. März 44 v. Chr. ermordet?`,
      answer_1: "Julius Caesar",
      answer_2: "Alexander der Große",
      answer_3: "Augustus",
      answer_4: "Nero",
      right_answer: 1,
    },
    {
      question: "Was war die Magna Carta?",
      answer_1: "Ein Vertrag zwischen Deutschland und Frankreich",
      answer_2: "Ein mittelalterliches Grundlagendokument",
      answer_3: "Ein antikes Handelsschiff",
      answer_4: "Ein berühmtes Gemälde der Renaissance",
      right_answer: 2,
    },
    {
      question: "Welches Ereignis führte zur Französischen Revolution?",
      answer_1: "Der Schwarze Tod",
      answer_2: "Die Entdeckung Amerikas",
      answer_3: "Die Hinrichtung Ludwig XVI.",
      answer_4: "Der Sturz der Berliner Mauer",
      right_answer: 3,
    }
  ];
  
  let scienceQuestions = [
    {
      question: "Welche Einheit misst die Intensität von Erdbeben?",
      answer_1: "Watt",
      answer_2: "Joule",
      answer_3: "Hertz",
      answer_4: "Richter",
      right_answer: 4,
      topic: "science",
    },
    {
      question: "Was ist die chemische Formel für Wasser?",
      answer_1: "CO2",
      answer_2: "H2O",
      answer_3: "O2",
      answer_4: "CH4",
      right_answer: 2,
      topic: "science",
    },
    {
      question: "Welches Gas macht etwa 78% der Erdatmosphäre aus?",
      answer_1: "Sauerstoff",
      answer_2: "Stickstoff",
      answer_3: "Kohlendioxid",
      answer_4: "Wasserstoff",
      right_answer: 2,
      topic: "science",
    },
    {
      question: "Was ist die kleinste Einheit eines chemischen Elements?",
      answer_1: "Molekül",
      answer_2: "Atom",
      answer_3: "Isotop",
      answer_4: "Ion",
      right_answer: 2,
      topic: "science",
    },
    {
      question: "Welcher Planet ist der dritte in unserem Sonnensystem?",
      answer_1: "Mars",
      answer_2: "Venus",
      answer_3: "Erde",
      answer_4: "Jupiter",
      right_answer: 3,
      topic: "science",
    },
  ];
  
let sportQuestions =[
    
    {
      question: "Welcher Dinosaurier wird als 'König der Echsen' bezeichnet?",
      answer_1: "Tyrannosaurus Rex",
      answer_2: "Stegosaurus",
      answer_3: "Triceratops",
      answer_4: "Velociraptor",
      right_answer: 1,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen langen Hals bekannt ist?",
      answer_1: "Brachiosaurus",
      answer_2: "Diplodocus",
      answer_3: "Parasaurolophus",
      answer_4: "Apatosaurus",
      right_answer: 1,
    },
    {
      question: "Welche Dinosaurier-Art war ein flugfähiger Reptil?",
      answer_1: "Tyrannosaurus Rex",
      answer_2: "Velociraptor",
      answer_3: "Pterodactylus",
      answer_4: "Triceratops",
      right_answer: 3,
    },
    {
      question: "In welcher geologischen Periode lebten die meisten Dinosaurier?",
      answer_1: "Jurazeit",
      answer_2: "Trias",
      answer_3: "Kreidezeit",
      answer_4: "Devon",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier wird auch als 'Dreihorngesicht' bezeichnet?",
      answer_1: "Stegosaurus",
      answer_2: "Triceratops",
      answer_3: "Ankylosaurus",
      answer_4: "Parasaurolophus",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier war ein großer, fleischfressender Theropode mit kleinen Armen?",
      answer_1: "Allosaurus",
      answer_2: "Spinosaurus",
      answer_3: "Velociraptor",
      answer_4: "Tyrannosaurus Rex",
      right_answer: 4,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seine dreieckigen Knochenplatten auf dem Rücken bekannt ist?",
      answer_1: "Stegosaurus",
      answer_2: "Ankylosaurus",
      answer_3: "Triceratops",
      answer_4: "Pachycephalosaurus",
      right_answer: 1,
    },
    {
      question: "Welche Dinosaurier-Art war ein Pflanzenfresser mit einem langen, schmalen Schädel und einem 'Horn' auf der Nase?",
      answer_1: "Parasaurolophus",
      answer_2: "Styracosaurus",
      answer_3: "Einiosaurus",
      answer_4: "Protoceratops",
      right_answer: 2,
    },
    {
      question: "In welchem Jahrhundert wurden die ersten Dinosaurier-Fossilien entdeckt?",
      answer_1: "18. Jahrhundert",
      answer_2: "19. Jahrhundert",
      answer_3: "20. Jahrhundert",
      answer_4: "21. Jahrhundert",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier hatte vermutlich Federn und wird oft als Übergangsform zwischen Dinosauriern und Vögeln betrachtet?",
      answer_1: "Archaeopteryx",
      answer_2: "Microraptor",
      answer_3: "Sinosauropteryx",
      answer_4: "Velociraptor",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Vogelbeckensaurier' bezeichnet?",
      answer_1: "Allosaurus",
      answer_2: "Compsognathus",
      answer_3: "Archaeopteryx",
      answer_4: "Troodon",
      right_answer: 3,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seine langen Stacheln auf dem Schwanz bekannt ist?",
      answer_1: "Stegosaurus",
      answer_2: "Spinosaurus",
      answer_3: "Ouranosaurus",
      answer_4: "Dimetrodon",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier gehört zu den 'Hörnchen-Gesichtern'?",
      answer_1: "Triceratops",
      answer_2: "Pentaceratops",
      answer_3: "Chasmosaurus",
      answer_4: "Protoceratops",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier hatte eine gewundene Knochenkuppel auf dem Kopf?",
      answer_1: "Parasaurolophus",
      answer_2: "Corythosaurus",
      answer_3: "Tsintaosaurus",
      answer_4: "Edmontosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Räuber mit Kamm' bezeichnet?",
      answer_1: "Dilophosaurus",
      answer_2: "Carnotaurus",
      answer_3: "Suchomimus",
      answer_4: "Ceratosaurus",
      right_answer: 2,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen massiven Schädel und kurzen Nacken bekannt ist?",
      answer_1: "Pachycephalosaurus",
      answer_2: "Stygimoloch",
      answer_3: "Dracorex",
      answer_4: "Homalocephale",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier hatte einen langen, dünnen Schwanz mit einer Peitschenspitze?",
      answer_1: "Brachiosaurus",
      answer_2: "Apatosaurus",
      answer_3: "Diplodocus",
      answer_4: "Sauroposeidon",
      right_answer: 2,
    },
    {
      question: "In welcher geologischen Periode lebte der Velociraptor?",
      answer_1: "Jurazeit",
      answer_2: "Kreidezeit",
      answer_3: "Trias",
      answer_4: "Devon",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier wird als 'Langhals-Dinosaurier' bezeichnet?",
      answer_1: "Brachiosaurus",
      answer_2: "Diplodocus",
      answer_3: "Apatosaurus",
      answer_4: "Mamenchisaurus",
      right_answer: 4,
    },
    {
      question: "Welcher Dinosaurier hatte ein massives, gekrümmtes Horn auf der Nase?",
      answer_1: "Styracosaurus",
      answer_2: "Centrosaurus",
      answer_3: "Einiosaurus",
      answer_4: "Pachyrhinosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Fleischfressender Saurier' bezeichnet?",
      answer_1: "Carnotaurus",
      answer_2: "Allosaurus",
      answer_3: "Spinosaurus",
      answer_4: "Giganotosaurus",
      right_answer: 1,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen großen Kamm auf dem Kopf bekannt ist?",
      answer_1: "Parasaurolophus",
      answer_2: "Corythosaurus",
      answer_3: "Lambeosaurus",
      answer_4: "Hadrosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier hatte ein langes, schmales Gebiss und ernährte sich vorwiegend von Fisch?",
      answer_1: "Baryonyx",
      answer_2: "Suchomimus",
      answer_3: "Spinosaurus",
      answer_4: "Irritator",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Täuschkünstler' bezeichnet und hatte möglicherweise Federn?",
      answer_1: "Archaeopteryx",
      answer_2: "Deinonychus",
      answer_3: "Microraptor",
      answer_4: "Oviraptor",
      right_answer: 4,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen massiven Schädel mit Knochenstacheln bekannt ist?",
      answer_1: "Stegosaurus",
      answer_2: "Pachycephalosaurus",
      answer_3: "Kentrosaurus",
      answer_4: "Einiosaurus",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier hatte riesige, säbelförmige Zähne und war ein Fleischfresser?",
      answer_1: "Tyrannosaurus Rex",
      answer_2: "Spinosaurus",
      answer_3: "Carcharodontosaurus",
      answer_4: "Giganotosaurus",
      right_answer: 3,
    },
    {
      question: "In welcher geologischen Periode lebte der Stegosaurus?",
      answer_1: "Jurazeit",
      answer_2: "Kreidezeit",
      answer_3: "Trias",
      answer_4: "Devon",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Fliegender Reptil' bezeichnet und konnte fliegen?",
      answer_1: "Pteranodon",
      answer_2: "Dimorphodon",
      answer_3: "Quetzalcoatlus",
      answer_4: "Rhamphorhynchus",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier hatte einen massiven Schädel und war bekannt für seine starken Kiefermuskeln?",
      answer_1: "Carnotaurus",
      answer_2: "Tyrannosaurus Rex",
      answer_3: "Allosaurus",
      answer_4: "Giganotosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wurde nach dem Paläontologen Roy Chapman Andrews benannt?",
      answer_1: "Andrewsarchus",
      answer_2: "Andrewsaurus",
      answer_3: "Andrewslophus",
      answer_4: "Andrewsornis",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wurde nach einer mythischen Kreatur aus der chinesischen Mythologie benannt?",
      answer_1: "Longosaurus",
      answer_2: "Fengshuiosaurus",
      answer_3: "Qilongosaurus",
      answer_4: "Dragonsaurus",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier hatte eine auffällige, keulenartige Verdickung am Schwanz?",
      answer_1: "Ankylosaurus",
      answer_2: "Nodosaurus",
      answer_3: "Edmontonia",
      answer_4: "Saichania",
      right_answer: 1,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen langen, dünnen Hals und kleine Kopffortsätze bekannt ist?",
      answer_1: "Nigersaurus",
      answer_2: "Amargasaurus",
      answer_3: "Brachytrachelopan",
      answer_4: "Dicraeosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Schrecklicher Kralle' übersetzt und war ein gefiederter Dromaeosauride?",
      answer_1: "Deinonychus",
      answer_2: "Velociraptor",
      answer_3: "Utahraptor",
      answer_4: "Microraptor",
      right_answer: 2,
    },
    {
      question: "In welchem heutigen Land wurden die meisten Fossilien des Spinosaurus gefunden?",
      answer_1: "Ägypten",
      answer_2: "Brasilien",
      answer_3: "Marokko",
      answer_4: "Sudan",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier hatte ein hornähnliches Gebilde auf der Nase?",
      answer_1: "Styracosaurus",
      answer_2: "Pentaceratops",
      answer_3: "Centrosaurus",
      answer_4: "Protoceratops",
      right_answer: 4,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seine starken Hinterbeine und den dreizinkigen Fuß bekannt ist?",
      answer_1: "Dilophosaurus",
      answer_2: "Carnotaurus",
      answer_3: "Allosaurus",
      answer_4: "Coelophysis",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier wird als 'Giganueros' übersetzt und war ein riesiger Theropode?",
      answer_1: "Giganotosaurus",
      answer_2: "Gigantosaurus",
      answer_3: "Giganticusaurus",
      answer_4: "Gigasaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier hatte vermutlich einen großen, bogenförmigen Schnabel und war ein Pflanzenfresser?",
      answer_1: "Iguanodon",
      answer_2: "Ouranosaurus",
      answer_3: "Oviraptor",
      answer_4: "Parasaurolophus",
      right_answer: 1,
    },
    {
      question: "In welcher geologischen Periode lebte der Triceratops?",
      answer_1: "Jurazeit",
      answer_2: "Kreidezeit",
      answer_3: "Trias",
      answer_4: "Devon",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier wurde nach einer mythischen Kreatur aus der chinesischen Mythologie benannt?",
      answer_1: "Longosaurus",
      answer_2: "Fengshuiosaurus",
      answer_3: "Qilongosaurus",
      answer_4: "Dragonsaurus",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier hatte eine auffällige, keulenartige Verdickung am Schwanz?",
      answer_1: "Ankylosaurus",
      answer_2: "Nodosaurus",
      answer_3: "Edmontonia",
      answer_4: "Saichania",
      right_answer: 1,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seinen langen, dünnen Hals und kleine Kopffortsätze bekannt ist?",
      answer_1: "Nigersaurus",
      answer_2: "Amargasaurus",
      answer_3: "Brachytrachelopan",
      answer_4: "Dicraeosaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier wird als 'Schrecklicher Kralle' übersetzt und war ein gefiederter Dromaeosauride?",
      answer_1: "Deinonychus",
      answer_2: "Velociraptor",
      answer_3: "Utahraptor",
      answer_4: "Microraptor",
      right_answer: 2,
    },
    {
      question: "In welchem heutigen Land wurden die meisten Fossilien des Spinosaurus gefunden?",
      answer_1: "Ägypten",
      answer_2: "Brasilien",
      answer_3: "Marokko",
      answer_4: "Sudan",
      right_answer: 3,
    },
    {
      question: "Welcher Dinosaurier hatte ein hornähnliches Gebilde auf der Nase?",
      answer_1: "Styracosaurus",
      answer_2: "Pentaceratops",
      answer_3: "Centrosaurus",
      answer_4: "Protoceratops",
      right_answer: 4,
    },
    {
      question: "Wie wird der Dinosaurier genannt, der für seine starken Hinterbeine und den dreizinkigen Fuß bekannt ist?",
      answer_1: "Dilophosaurus",
      answer_2: "Carnotaurus",
      answer_3: "Allosaurus",
      answer_4: "Coelophysis",
      right_answer: 2,
    },
    {
      question: "Welcher Dinosaurier wird als 'Giganueros' übersetzt und war ein riesiger Theropode?",
      answer_1: "Giganotosaurus",
      answer_2: "Gigantosaurus",
      answer_3: "Giganticusaurus",
      answer_4: "Gigasaurus",
      right_answer: 1,
    },
    {
      question: "Welcher Dinosaurier hatte vermutlich einen großen, bogenförmigen Schnabel und war ein Pflanzenfresser?",
      answer_1: "Iguanodon",
      answer_2: "Ouranosaurus",
      answer_3: "Oviraptor",
      answer_4: "Parasaurolophus",
      right_answer: 1,
    },
    {
      question: "In welcher geologischen Periode lebte der Triceratops?",
      answer_1: "Jurazeit",
      answer_2: "Kreidezeit",
      answer_3: "Trias",
      answer_4: "Devon",
      right_answer: 2,
    },
  ];
  
let geoQuestions =[
    {
      question: "Was ist der größte Kontinent der Erde?",
      answer_1: "Europa",
      answer_2: "Afrika",
      answer_3: "Asien",
      answer_4: "Nordamerika",
      right_answer: 3,
    },
    {
      question: "Welcher Fluss ist der längste auf der Erde?",
      answer_1: "Nil",
      answer_2: "Amazonas",
      answer_3: "Jangtse",
      answer_4: "Mississippi",
      right_answer: 2,
    },
    {
      question: "Welcher Ozean liegt zwischen Nordamerika und Europa?",
      answer_1: "Atlantischer Ozean",
      answer_2: "Pazifischer Ozean",
      answer_3: "Indischer Ozean",
      answer_4: "Südlicher Ozean",
      right_answer: 1,
    },
    {
      question: "Welches Land hat die meisten Einwohner auf der Welt?",
      answer_1: "Indien",
      answer_2: "China",
      answer_3: "USA",
      answer_4: "Russland",
      right_answer: 2,
    },
  ];